name: mindful
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# NOTE: If you bump the version than also change it version in [AppConstants]
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Runtime dependencies
  # UI
  flutter_onboarding_slider: ^1.0.11
  fluentui_system_icons: ^1.1.210
  fl_chart: ^0.63.0
  flutter_riverpod: ^2.4.0

  # Animation
  flutter_animate: ^4.2.0+1
  skeletonizer: ^1.4.1+1

  # Database and Storage
  isar: ^3.1.0+1
  path_provider: ^2.1.2
  isar_flutter_libs: ^3.1.0+1

  # Util
  sliver_tools: ^0.2.12
  flutter_heatmap_calendar: ^1.0.5
  animated_flip_counter: ^0.3.4
  flutter_confetti: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Development dependencies.
  # Generator =>  dart run build_runner build
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Onboarding
    - assets/illustrations/onboarding_1.png
    - assets/illustrations/onboarding_2.png
    - assets/illustrations/onboarding_3.png
    - assets/illustrations/onboarding_4.png
    - assets/illustrations/onboarding_5.png
    - assets/illustrations/onboarding_6.png

    # Short content platform's icons
    - assets/icons/instaReels.png
    - assets/icons/fbReels.png
    - assets/icons/snapSpotlight.png
    - assets/icons/ytShorts.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
